# Generated by Django 2.0.6 on 2018-07-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('speed', models.SmallIntegerField()),
                ('ram', models.SmallIntegerField()),
                ('hd', models.FloatField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('screen', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('speed', models.SmallIntegerField()),
                ('ram', models.SmallIntegerField()),
                ('hd', models.FloatField()),
                ('cd', models.CharField(max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=1)),
                ('type', models.CharField(max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('maker', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='printer',
            name='model',
            field=models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.DO_NOTHING, to='comp_info.Product'),
        ),
        migrations.AddField(
            model_name='pc',
            name='model',
            field=models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.DO_NOTHING, to='comp_info.Product'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model',
            field=models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.DO_NOTHING, to='comp_info.Product'),
        ),
    ]
